### ISSUE TITLE
-fno-inline-functions-called-once is now an error on clang (OS X 10.10)

### ISSUE THREAD

**Issue by nemith** [Juniper/libslax#24]
With the 10.10 preview and the updated clang the -fno-inline-functions-called-once is not a valid option and used to be just a warning, but now is a full error.

    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
    Making all in libslax
      CC       jsonwriter.lo
      CC       jsonlexer.lo
      CC       slaxdebugger.lo
      CC       slaxdyn.lo
    clangclang: : errorerror: : unknown argument: '-fno-inline-functions-called-once' [-Wunused-command-line-argument-hard-error-in-future]unknown argument: '-fno-inline-functions-called-once' [-Wunused-command-line-argument-hard-error-in-future]

    clang: error: unknown argument: '-fno-inline-functions-called-once' [-Wunused-command-line-argument-hard-error-in-future]
    clangclang: : notenote: : this will be a hard error (cannot be downgraded to a warning) in the futurethis will be a hard error (cannot be downgraded to a warning) in the future

    clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
    clang: error: unknown argument: '-fno-inline-functions-called-once' [-Wunused-command-line-argument-hard-error-in-future]
    clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
    make[2]: *** [jsonwriter.lo] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: *** [slaxdebugger.lo] Error 1
    make[2]: *** [jsonlexer.lo] Error 1
    make[2]: *** [slaxdyn.lo] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

Maybe need to check for clang in automake and make this an optional flag?

**Comment by philshafer** [comment]
This has been fixed.  The flag is no longer passed to non-gcc compilers
