### ISSUE TITLE
libstax 0-21.x requires GCC 5 or later.

### ISSUE THREAD

**Issue by rgwilton** [Juniper/libslax#42]
Hi,

I failed to compile this library (libstax-0-21.1) under xbuntu (in a VM) due to the following error:

Making all in libpsu
make[1]: Entering directory `/home/rwilton/datastores-draft/libslax-0.21.0/build/libpsu'
  CC       psualloc.lo
  CC       psuasprintf.lo
  CC       psubase64.lo
  CC       psucpu.lo
../../libpsu/psucpu.c: In function ‘psu_cpu_get_info’:
../../libpsu/psucpu.c:108:5: error: inconsistent operand constraints in an ‘asm’
     asm volatile
     ^
make[1]: *** [psucpu.lo] Error 1
make[1]: Leaving directory `/home/rwilton/datastores-draft/libslax-0.21.0/build/libpsu'
make: *** [all-recursive] Error 1

After a bit of googling, it appears that this error is a known issue with my older gcc version:
  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

Updating to a version 5 of gcc fixed the problem:
  gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~14.04) 

Rob

**Comment by philshafer** [comment]
Fixed in 'develop' branch
