### ISSUE TITLE
build error: aclocal not found

### ISSUE THREAD

**Issue by 2-www** [Juniper/libslax#64]
i am trying to build this on debian unstable and i get this:
```
bash-5.2$ sh bin/setup.sh 
Using autoreconf (GNU Autoconf) 2.72
Can't exec "aclocal": Немає такого файла або каталогу at /usr/share/autoconf/Autom4te/FileUtils.pm line 299.
autoreconf: error: aclocal failed with exit status: 2
Failed to create configure script
bash-5.2$ 
```

(anyway, i'm trying to port it to meson, would you accept a merge request to add meson.build files?)

**Comment by philshafer** [comment]
$ port provides `which aclocal`
/opt/local/bin/aclocal is provided by: automake

I've no familiarity with meson, and while I am sympathetic to anyone dislike of automake/etc, I still think they are the "table stakes" for open source, however annoying.

Thanks,
 Phil
